-- CreateTable
CREATE TABLE `User` (
    `id` VARCHAR(191) NOT NULL,
    `email` VARCHAR(150) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Transaction` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `amount` DOUBLE NOT NULL,
    `currency` CHAR(4) NOT NULL DEFAULT 'IRR',
    `category` ENUM('DAILY_PURCHASES', 'MONEY_TRANSFER', 'FOOD', 'CASH_WITHDRAWAL', 'HEALTH_BEAUTY', 'BILLS', 'FASHION', 'TRANSPORT', 'HOUSING', 'ENTERTAINMENT', 'CULTURE_ART', 'SAVINGS_INVESTMENT', 'SPORT', 'GIFT', 'LOAN_INSTALLMENT', 'OTHER') NOT NULL DEFAULT 'OTHER',
    `intent` ENUM('PLANNED', 'IMPULSE', 'OBLIGATION') NOT NULL,
    `emotion` ENUM('REGRET', 'SATISFACTION', 'STRESS', 'NEUTRAL', 'GUILT', 'RELIEF') NOT NULL,
    `note` VARCHAR(500) NULL,
    `occurredAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `Transaction_userId_occurredAt_idx`(`userId`, `occurredAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Transaction` ADD CONSTRAINT `Transaction_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
