-- AlterTable
ALTER TABLE `Transaction` MODIFY `category` ENUM('DAILY_EXPENSES', 'TRANSFERS', 'SALARY', 'FOOD_AND_DRINKS', 'CASH', 'HEALTH_AND_BEAUTY', 'UTILITIES', 'CLOTHING', 'TRANSPORTATION', 'HOUSING', 'ENTERTAINMENT', 'ART_AND_CULTURE', 'SAVINGS_AND_INVESTMENTS', 'SPORTS', 'GIFTS_AND_DONATIONS', 'LOAN_PAYMENTS', 'OTHER') NOT NULL DEFAULT 'OTHER';
