import { COMMON_CONSTANT } from '../../common/constants/common.constant';

export const INSIGHTS_CONSTANT = {
  QUEUE_NAME: 'insights',
  QUEUE_LIMITER: { max: 3, duration: 1000 * 60 }, // OPENAI Limits: 3 RPM (object keys must be lowercase)

  LENGTH: {
    INSIGHT_TRANSACTIONS: { MIN: 10, MAX: 20 }, // minimum and maximum required 'EXPENSE' transactions for insight generation
  },

  ERROR: {
    PERIOD_FORMAT: COMMON_CONSTANT.ERROR.PERIOD_FORMAT,
    INSIGHT_NOT_FOUND: (id: string) => `Insight with id/period ${id} not found`,
  },

  FIELD_DESCRIPTION: {
    ID: 'Unique identifier (UUID) for the insight',
    USER_ID: 'Unique identifier (UUID) for the user',
    PERIOD: COMMON_CONSTANT.FIELD_DESCRIPTION.PERIOD,
    CONTENT: 'Content of the insight generated by the LLM',
    LLM_MODEL: 'LLM model used to generate the insight',
    CREATED_AT: 'Timestamp indicating when the insight was created',
    UPDATED_AT: 'Timestamp indicating when the insight was updated',
    LLM_REQUEST_ID: 'Request ID of the LLM request received from the LLM',
  },
};
